# Generated by Django 5.1.1 on 2024-09-10 11:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование типа устройства')),
            ],
            options={
                'verbose_name': 'Тип устройства',
                'verbose_name_plural': 'Типы устройств',
                'db_table': 'device_type',
            },
        ),
        migrations.CreateModel(
            name='TechPlace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('address', models.TextField(db_column='address', verbose_name='Адрес местонахождение устройства')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта местонахождения устройства')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота местонахождения устройства')),
            ],
            options={
                'verbose_name': 'Местонахождение устройства',
                'verbose_name_plural': 'Местонахождение устройств',
                'db_table': 'tech_place',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование устройства')),
                ('date_add', models.DateTimeField(verbose_name='Дата добавления устройства')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='network.device', verbose_name='Родительское устройство')),
                ('type', models.ForeignKey(db_column='device_type_id', on_delete=django.db.models.deletion.PROTECT, to='network.devicetype', verbose_name='Тип устройства')),
                ('tech_place', models.ForeignKey(db_column='tech_place_id', on_delete=django.db.models.deletion.PROTECT, to='network.techplace', verbose_name='Местонахождение устройства')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
                'db_table': 'device',
            },
        ),
    ]
