# Generated by Django 5.1.1 on 2024-09-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_device_id_alter_devicetype_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления устройства'),
        ),
    ]
